# Generated by Django 5.0.4 on 2024-05-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, upload_to='project/'),
        ),
    ]
