# Generated by Django 5.0.4 on 2024-05-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_category_project_location_project_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mockup_type', models.TextField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='project/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
