# Generated by Django 5.0.4 on 2024-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_mockup_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
