# Generated by Django 5.0.4 on 2024-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_project_category_alter_project_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='image',
            field=models.FileField(null=True, upload_to='project/'),
        ),
    ]
