# Generated by Django 5.0.4 on 2024-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_mockup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='image_or_photo',
            field=models.BooleanField(null=True),
        ),
    ]
