# Generated by Django 5.0.4 on 2024-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_mockup_image_or_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockup',
            old_name='image',
            new_name='file_1',
        ),
        migrations.RemoveField(
            model_name='mockup',
            name='image_or_photo',
        ),
        migrations.AddField(
            model_name='mockup',
            name='file_2',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='mockup',
            name='file_3',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='mockup',
            name='main_file',
            field=models.FileField(null=True, upload_to='project/'),
        ),
    ]
