# Generated by Django 5.0.4 on 2024-05-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_rename_image_mockup_file_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='mockup_type',
            field=models.TextField(choices=[('phone', 'phone'), ('iphone', 'iphone 15'), ('phone prototype', 'phone Prototype'), ('tablet', 'ipad'), ('mac_pro', 'mac pro'), ('mac_pro_studio', 'mac pro studio'), ('prototype', 'prototype')], max_length=30, null=True),
        ),
    ]
