# Generated by Django 5.0.4 on 2024-05-18 21:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_mockup_mockup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='background_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='mockup_type',
            field=models.TextField(choices=[('phone', 'phone'), ('iphone 15', 'iphone 15'), ('phone prototype', 'phone Prototype'), ('tablet', 'ipad'), ('mac pro', 'mac pro'), ('mac pro studio', 'mac pro studio'), ('prototype', 'prototype')], max_length=30, null=True),
        ),
    ]
