# Generated by Django 5.0.4 on 2024-05-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_mockup_background_color_alter_mockup_mockup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='background_color',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
