# Generated by Django 5.0.4 on 2024-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_contact_alter_mockup_mockup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='services',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
