# Generated by Django 5.0.4 on 2024-05-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_contact_email_contact_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='organization_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='services',
            new_name='service',
        ),
    ]
