# Generated by Django 5.0.4 on 2024-05-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_rename_organization_name_contact_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
