# Generated by Django 5.0.4 on 2024-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('middel_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('work_1', models.CharField(max_length=30, null=True)),
                ('work_2', models.CharField(max_length=30, null=True)),
                ('about_1', models.CharField(max_length=30, null=True)),
                ('about_2', models.CharField(max_length=30, null=True)),
                ('about_3', models.CharField(max_length=30, null=True)),
                ('about_4', models.CharField(max_length=30, null=True)),
                ('skill_1', models.CharField(max_length=30, null=True)),
                ('skill_2', models.CharField(max_length=30, null=True)),
                ('skill_3', models.CharField(max_length=30, null=True)),
                ('skill_1_title', models.CharField(max_length=30, null=True)),
                ('skill_2_title', models.CharField(max_length=30, null=True)),
                ('skill_3_title', models.CharField(max_length=30, null=True)),
                ('edition', models.CharField(max_length=30, null=True)),
                ('social_1', models.URLField(null=True)),
                ('social_2', models.URLField(null=True)),
                ('social_3', models.URLField(null=True)),
                ('social_4', models.URLField(null=True)),
                ('social_1_name', models.CharField(max_length=30, null=True)),
                ('social_2_name', models.CharField(max_length=30, null=True)),
                ('social_3_name', models.CharField(max_length=30, null=True)),
                ('social_4_name', models.CharField(max_length=30, null=True)),
                ('about_title', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='design',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='development',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visible_home',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visible_work',
            field=models.BooleanField(null=True),
        ),
    ]
