# Generated by Django 5.0.4 on 2024-07-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_site_data_project_design_project_development_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='url_project',
        ),
    ]
