# Generated by Django 5.0.4 on 2024-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_project_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.ImageField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_3',
            field=models.ImageField(null=True, upload_to='project/'),
        ),
    ]
