# Generated by Django 5.0.4 on 2024-07-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_alter_project_image_alter_project_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_data',
            old_name='about_3',
            new_name='about_2_title',
        ),
        migrations.RenameField(
            model_name='site_data',
            old_name='about_4',
            new_name='about_title_2',
        ),
        migrations.RenameField(
            model_name='site_data',
            old_name='skill_1',
            new_name='business_data_1',
        ),
        migrations.RenameField(
            model_name='site_data',
            old_name='skill_1_title',
            new_name='business_data_2',
        ),
        migrations.RenameField(
            model_name='site_data',
            old_name='skill_2',
            new_name='business_data_3',
        ),
        migrations.RenameField(
            model_name='site_data',
            old_name='skill_2_title',
            new_name='contact_title_1',
        ),
        migrations.RenameField(
            model_name='site_data',
            old_name='skill_3',
            new_name='contact_title_2',
        ),
        migrations.RenameField(
            model_name='site_data',
            old_name='skill_3_title',
            new_name='contact_title_3',
        ),
        migrations.AddField(
            model_name='site_data',
            name='contact_title_4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='desc_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='desc_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='horizontal_items_1',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='site_data',
            name='horizontal_items_2',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='site_data',
            name='horizontal_items_3',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='site_data',
            name='horizontal_items_4',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='site_data',
            name='horizontal_items_5',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='site_data',
            name='horizontal_items_6',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='site_data',
            name='horizontal_items_7',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='site_data',
            name='horizontal_items_8',
            field=models.FileField(null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='site_data',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='service_1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='service_1_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='service_2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='service_2_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='service_3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='service_3_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='work_title_1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site_data',
            name='work_title_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site_data',
            name='about_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site_data',
            name='about_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site_data',
            name='edition',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
